[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
loan_program = "DeDyjnQopMBxYJMT8UYyjKCZ1ZcYTrCQLmkS2dFzezgY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tamur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
